name: Deploy to GCP App Engine
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
      #   with:
      #     version: 290.0.1
      #     service_account_key: '${{ secrets.GCP_SA_KEY }}'
      #     project_id: your-gcp-project-id
      # - name: Deploy to App Engine
      #   run: |
      #     gcloud app deploy --quiet
